updates:
  - assignees:
      - JoshuaKGoldberg
    commit-message:
      include: scope
      prefix: build
    directory: /
    labels:
      - dependencies
      - npm
    package-ecosystem: npm
    schedule:
      interval: daily
    target-branch: main
version: 2
